### ISSUE TITLE
CtrlPSwitch error preventing plugin operation

### ISSUE THREAD

**Issue by valentinrusu-movidius** [ivan-cukic/vim-ctrlp-switcher#7]
Hey Ivan,

Using VIM on Fedora Core 25:

> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jul 31 2017 08:46:24)
> Included patches: 1-823
> 

This used to work in my .vimrc:

```vim
 map <F4> :CtrlPSwitch<CR>
```

When I'm in some C/C++ source file, I hit F4 to go to the respective .h or .cpp counterpart and instead get this:

> Error detected while processing function ctrlp#init[22]..ctrlp#setlines[8]..ctrlp#switcher#init:                                                                             
> line   88:                                                                                                                                                                   
> Traceback (most recent call last):                                                                                                                                           
>   File "<string>", line 65, in <module>                                                                                                                                      
> TypeError: a bytes-like object is required, not 'str'                                                                                                                        
>                                                                                                                                                                              

I'm not sure since when it stopped working as I regularly update my plugins.

**Comment by ivan-cukic** [comment]
Hi Valentin,

I've noticed this as well, but had no time to investigate. I hope I'll have some time soon for it.

**Comment by ivan-cukic** [comment]
This should be fixed now
