### ISSUE TITLE
Would it be possible to use python instead of py3?

### ISSUE THREAD

**Issue by kshenoy** [ivan-cukic/vim-ctrlp-switcher#8]
I see that py3 is called [here](https://github.com/ivan-cukic/vim-ctrlp-switcher/blob/master/autoload/ctrlp/switcher.vim#L20) and [here](https://github.com/ivan-cukic/vim-ctrlp-switcher/blob/master/autoload/ctrlp/switcher.vim#L99). Is there a specific reason for using `py3` instead of `python`? 

I'm asking because I don't have access to vim compiled with python3 at work. ~~I replaced py3 and python and it seems to work fine.~~ Is there a way to make it work with just python?

I opened up two test files - test.h and test.cpp. If I open `CtrlPSwitcherBasic` from test.h, it shows test.cpp and I'm able to switch to it. However, if I open it from test.cpp then test.h is not shown.

**Comment by ivan-cukic** [comment]
Unfortunately, I do not have any system with python 2 enabled. I would not mind if somebody wanted to maintain a python 2 branch for it.

I'm closing for the time being - if anyone steps up for this, I'll try to help.
