### ISSUE TITLE
Is it possible to directly switch when there's only one match?

### ISSUE THREAD

**Issue by kshenoy** [ivan-cukic/vim-ctrlp-switcher#9]
eg. if I only have test.cpp and test.h and no other test* files. Then I'd like to switch directly between the two without having to select it manually (default behavior of a.vim and fswitch).

**Comment by ivan-cukic** [comment]
Not that I know. This is based on ctrlp and it always shows the list from what I can tell. I never considered it to be a problem - for me it brings more benefits while just having the downside of requiring one extra press of the Enter key.
